version: '3.9'

services:
  log-analyzer:
    build:
      context: .. 
      dockerfile: docker/Dockerfile.local
    ports:
      - "80:80"
    environment:
      - RUNENV=local
    volumes:
      - ../data:/app/data  # <--- Cambiamos ./ por ../ para subir un nivel
    networks:
      - log-analyzer-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Ruta relativa para portabilidad
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=citizix_dbzzz
    networks:
      - log-analyzer-network

networks:
  log-analyzer-network:
    driver: bridge